Implement Newton's method for iterative scheme for Poisson solve in MFIS
AMReX-Microelectronics/FerroX pull request #17
Opened 2022-09-16 03:03 UTC by prkkumar

2022-09-19 21:59 UTC, RevathiJambunathan commented on Source/main.cpp
> +    Real delta;
```suggestion
    Real delta = 1.e-6;
```

2022-09-19 21:59 UTC, RevathiJambunathan commented on Source/main.cpp
> +        delta = 1.e-6;
```suggestion
```

2022-09-19 23:09 UTC, ajnonaka commented on Source/main.cpp
> +    //alpha_cc.setVal(0.);
The MultiFabs "alpha_cc" and "f_prime" are redundant.  Use one or the other, and delete instances of the one you aren't using.

For what it's worth, the permittivity is stored in "beta_face" so to be consistent, I'd get rid of f_prime and just use alpha_cc.

2022-09-19 23:12 UTC, ajnonaka commented on Source/main.cpp
> +    mlabec.setScalars(-1.0, 1.0); // A = 1.0, B = 1.0
```suggestion
    mlabec.setScalars(-1.0, 1.0); // A = -1.0, B = 1.0 (solving (-A*alpha - div beta grad) phi = RHS
```

2022-09-19 23:14 UTC, ajnonaka commented on Source/main.cpp
> +    //mlmg.setVerbose(2);
Make mlmg_verbosity a parameter you can read in from the inputs file and pass it in here - useful for debugging.

2022-09-19 23:15 UTC, ajnonaka commented on Source/main.cpp
>          // MultiFab memory usage
Fix indentation starting from here to the bottom.

2022-09-19 23:20 UTC, ajnonaka commented on Source/main.cpp
> +    MultiFab PoissonRHS_phi_plus_delta(ba, dm, 1, 0);
You could make these local MultiFabs within dF_dPhi (simplify main, and pass around less stuff)

2022-09-19 23:22 UTC, ajnonaka commented on Source/ElectrostaticSolver.H
> +             MultiFab&      PoissonRHS_phi_plus_delta,
General style comment - with so many arguments it's probably useful to use "const MultiFab&" in instances where the input parameter is meant to be read-only.  This change would have to propagate across many functions in the code (you can't just fix it here, you have to fix it within all the functions called within as well).  It's kind of hard to tell exactly what this function is doing without either the "consts" or a comment at the top explicitly stating what this function is doing (e.g., "Compute f_prime = ..."

2022-09-19 23:27 UTC, ajnonaka requested changes
Looks pretty good - some of my comments should be addressed, some can wait for a future PR (you'll know which are which).

2022-09-22 00:48 UTC, prkkumar commented on Source/main.cpp
> +    MultiFab PoissonRHS_phi_plus_delta(ba, dm, 1, 0);
done.

2022-09-22 00:48 UTC, prkkumar commented on Source/main.cpp
>          // MultiFab memory usage
done.

2022-09-22 00:49 UTC, prkkumar commented on Source/main.cpp
> +    //mlmg.setVerbose(2);
done. I set the default to 1 for cleaner stdout. We can set it to 2 through input file for debugging etc..

2022-09-22 00:50 UTC, prkkumar commented on Source/main.cpp
> +    //alpha_cc.setVal(0.);
Done. Going with alpha_cc as you suggested.

2022-09-23 17:53 UTC, prkkumar commented on Source/ElectrostaticSolver.H
> +             MultiFab&      PoissonRHS_phi_plus_delta,
Should we address it in the next PR? I also plan to use namespace for storing constants that I pass around as input parameters in many functions. 

Next PR could be devoted to clean up issues to address this comment and to use namespace (https://github.com/AMReX-Microelectronics/FerroX/issues/18).

2022-09-27 16:28 UTC, ajnonaka commented on Source/ElectrostaticSolver.cpp
> +        }
```suggestion
        LinComb(alpha_cc, 1./delta, PoissonRHS_phi_plus_delta, 0, -1./delta, PoissonRHS, 0, 0, 1, 0);
```

2022-09-27 16:29 UTC, ajnonaka commented on Source/ElectrostaticSolver.cpp
> +        }
```suggestion
        LinComb(alpha_cc, 1./delta, PoissonRHS_phi_plus_delta, 0, -1./delta, PoissonRHS, 0, 0, 1, 0);
```

2022-09-27 16:35 UTC, ajnonaka commented on Source/main.cpp
> +    //alpha_cc.setVal(0.);
Delete lines 272-274

2022-09-27 16:35 UTC, ajnonaka approved these changes
Approve pending the two suggestions.

2022-09-27 16:51 UTC, merged